name: Release new version
on:
  workflow_dispatch:

jobs:
  release:
    uses: $githubUserNoSpaceLowercase$/workflows/.github/workflows/release.yml@main
    secrets:
      PAT: \${{ secrets.PAT }}  
    