name: Generate README and scaladoc
on:
  workflow_dispatch:
  push:
    branches: [ master, main ]
    paths:
      - '.github/site.yml'
      - 'src/docs/**'
      - 'src/site/**'
      - '*.scala' 

jobs:
  site:
    uses: $githubUserNoSpaceLowercase$/workflows/.github/workflows/site.yml@main
    with:
      author_name: $githubUser$
      author_email: $githubEmail$
    secrets:
      PAT: \${{ secrets.PAT }}  
    